apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-initial-secrets
  namespace: gitlab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-initial-secrets
    creationPolicy: Owner
  data:
    - secretKey: initial-root-password
      remoteRef:
        key: app-gitlab-initial-root-password
