apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-registry-data
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-csi
  resources:
    requests:
      storage: 20Gi
