apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- webui-statefulset.yaml
- webui-service.yaml
- http-route.yaml
- openwebui-secrets-external.yaml
- litellm-api-key.yaml
- openwebui-qdrant-api-key.yaml
- pipelines/
- pipelines-secret.yaml
- pipelines-pvc.yaml
- pipelines-deployment.yaml
- pipelines-service.yaml
- open-terminal-deployment.yaml
- open-terminal-service.yaml
- open-terminal-pvc.yaml
- open-terminal-externalsecret.yaml
- open-terminal-network-policy.yaml
- mcpo-configmap.yaml
- mcpo-external-secret.yaml
- mcpo-deployment.yaml
- mcpo-service.yaml
- mcpo-network-policy.yaml
