apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-openwebui-mcp-proxy-auth
  namespace: open-webui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    name: app-openwebui-mcp-proxy-auth
    creationPolicy: Owner
  data:
    - secretKey: MCP_PROXY_AUTH_TOKEN
      remoteRef:
        key: app-openwebui-mcp-proxy-auth
