apiVersion: v1
kind: Service
metadata:
  name: mcp-proxy
  namespace: open-webui
  labels:
    app: mcp-proxy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9090
      targetPort: http
      protocol: TCP
  selector:
    app: mcp-proxy
