apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-openwebui-mcpo-api-key
  namespace: open-webui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    name: app-openwebui-mcpo-api-key
    creationPolicy: Owner
  data:
    - secretKey: MCPO_API_KEY
      remoteRef:
        key: app-openwebui-mcpo-api-key
