apiVersion: v1
kind: Service
metadata:
  name: mcpo
  namespace: open-webui
  labels:
    app: mcpo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app: mcpo
