apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: open-terminal
  namespace: open-webui
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: open-terminal
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: open-webui
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
