apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-terminal-data
  namespace: open-webui
  labels:
    app.kubernetes.io/name: open-terminal
    backup.velero.io/backup-tier: Daily
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-csi
  resources:
    requests:
      storage: 10Gi
