apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-openwebui-open-terminal-api-key
  namespace: open-webui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: OPEN_TERMINAL_API_KEY
      remoteRef:
        key: app-openterminal-api
