apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-tracking-secret
  namespace: mlflow
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    name: mlflow-gitlab-tracking
    creationPolicy: Owner
  data:
    - secretKey: MLFLOW_TRACKING_TOKEN
      remoteRef:
        key: app-mlflow-gitlab-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-trigger-secret
  namespace: mlflow
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    name: mlflow-gitlab-trigger
    creationPolicy: Owner
  data:
    - secretKey: GITLAB_TRIGGER_TOKEN
      remoteRef:
        key: app-mlflow-gitlab-trigger-token
