backendStore:
  databaseMigration: true
  postgres:
    enabled: true
    host: mlflow-postgresql-rw.mlflow.svc.cluster.local
    port: 5432
    database: app
  existingDatabaseSecret:
    name: mlflow-postgresql-app
    passwordKey: password
    usernameKey: username

artifactRoot:
  s3:
    enabled: true
    bucket: mlflow-artifacts
    existingSecret:
      name: longhorn-minio-credentials
      keyOfAccessKeyId: AWS_ACCESS_KEY_ID
      keyOfSecretAccessKey: AWS_SECRET_ACCESS_KEY

extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: "https://truenas.peekoff.com:9000"
  AWS_DEFAULT_REGION: "us-east-1"
  MLFLOW_TRACKING_URI: "https://gitlab.peekoff.com/api/v4/projects/1/ml/mlflow/"

extraSecretNamesForEnvFrom:
  - mlflow-gitlab-tracking

extraArgs:
  workers: "1"

serverAllowedHosts:
  - "*"

service:
  type: ClusterIP
  port: 80
  containerPort: 5000

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 3Gi
