apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-hermes-session-secrets
  namespace: hermes
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    name: app-hermes-session-secrets
    creationPolicy: Owner
  data:
    - secretKey: HERMES_PASSWORD
      remoteRef:
        key: app-hermes-password
    - secretKey: HERMES_API_TOKEN
      remoteRef:
        key: app-hermes-api-token
    - secretKey: LITELLM_API_KEY
      remoteRef:
        key: app-hermes-litellm-key
