apiVersion: v1
kind: Service
metadata:
  name: hermes
  namespace: hermes
  labels:
    app.kubernetes.io/name: hermes
spec:
  selector:
    app.kubernetes.io/name: hermes
  ports:
    - name: http
      port: 3000
      targetPort: 3000
