---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: rustfs-access-key-gen
  namespace: rustfs
spec:
  length: 20
  digits: 4
  symbols: 0
  symbolCharacters: ""
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: rustfs-secret-key-gen
  namespace: rustfs
spec:
  length: 40
  digits: 8
  symbols: 0
  symbolCharacters: ""
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-credentials
  namespace: rustfs
spec:
  refreshInterval: "0"
  target:
    name: rustfs-credentials
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: rustfs-access-key-gen
      rewrite:
        - regexp:
            source: "^password$"
            target: "RUSTFS_ACCESS_KEY"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: rustfs-secret-key-gen
      rewrite:
        - regexp:
            source: "^password$"
            target: "RUSTFS_SECRET_KEY"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: rustfs-credentials
  namespace: rustfs
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: bitwarden-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: rustfs-credentials
  data:
    - match:
        secretKey: RUSTFS_ACCESS_KEY
        remoteRef:
          remoteKey: app-rustfs-access-key
    - match:
        secretKey: RUSTFS_SECRET_KEY
        remoteRef:
          remoteKey: app-rustfs-secret-key
