apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rustfs

helmCharts:
  - name: rustfs
    repo: https://charts.rustfs.com
    version: 0.8.0
    releaseName: rustfs
    namespace: rustfs
    valuesFile: values.yaml
    includeCRDs: false

resources:
  - namespace.yaml
  - externalsecret.yaml
  - network-policy.yaml
  - http-route.yaml
  - bucket-init.yaml

patches:
  - target:
      kind: Deployment
      name: rustfs
    patch: |
      - op: add
        path: /spec/template/spec/hostNetwork
        value: false
      - op: add
        path: /spec/template/spec/hostPID
        value: false
      - op: add
        path: /spec/template/spec/hostIPC
        value: false
