apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: arr
spec:
  replicas: 2  # Staging uses 2 replicas
  template:
    spec:
      containers:
      - name: .*  # This will match all containers
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi