apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-affine-env
  namespace: affine
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    name: es-affine-env
    creationPolicy: Owner
  data:
    - secretKey: REDIS_SERVER_HOST
      remoteRef:
        key: app-affine-redis-host
    - secretKey: AFFINE_REVISION
      remoteRef:
        key: app-affine-revision
    - secretKey: AFFINE_INDEXER_ENABLED
      remoteRef:
        key: app-affine-indexer-enabled
