apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patches:
- path: patches/deployment.yaml

labels:
- includeSelectors: true
  pairs:
    environment: prod
    app.kubernetes.io/managed-by: argocd
    dev.pc-tips: media