apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media
  namespace: argocd
  labels:
    dev.pc-tips: media
spec:
  generators:
    - git:
        repoURL: https://github.com/theepicsaxguy/homelab
        revision: main
        directories:
          - path: k8s/apps/media/*/dev
          - path: k8s/apps/media/*/staging
          - path: k8s/apps/media/*/prod
  template:
    metadata:
      name: '{{path.basename}}-{{path.parent.basename}}'
      labels:
        environment: '{{path.basename}}'
        dev.pc-tips: media
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: media
      source:
        repoURL: https://github.com/theepicsaxguy/homelab
        targetRevision: main
        path: '{{path}}'
      destination:
        name: in-cluster
        namespace: '{{path.parent.basename}}' # Uses the app name as namespace
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
