apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- allow-backup-minio.yaml
- allow-postgresql-access.yaml
namespace: database
labels:
- pairs:
    policy-type: database-audit
    network-policy: cilium-audit