#!/usr/bin/env bash
# fake kubectl
if [[ "$1" == "cordon" || "$1" == "drain" || "$1" == "uncordon" ]]; then
  echo "kubectl $@"
  exit 0
elif [[ "$1" == "get" ]]; then
  echo "NAME   STATUS"
  echo "node1  Ready"
  exit 0
elif [[ "$1" == "wait" ]]; then
  echo "node/$3 condition met"
  exit 0
else
  echo "kubectl $@"
  exit 0
fi
