apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: arr
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: app
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: torrent
  namespace: arr
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: torrent
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
