resources:
- ../base/configs
- ../base/auth
- ../base/controllers
- ../base/crds
- ../base/crossplane-crds
- ../base/monitoring
- ../base/network
- ../base/storage
- ../base/users
- ../base/vpn

patches:
- path: prod-patches.yaml

namespace: argocd

labels:
- includeSelectors: true
  pairs:
    environment: prod
    dev.pc-tips: infrastructure