---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runner-token
  namespace: gitlab-runner
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-runner-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        runner-token: "{{ .runnerToken }}"
        runner-registration-token: ""
  data:
    - secretKey: runnerToken
      remoteRef:
        key: app-gitlab-runner-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-ci-secrets
  namespace: gitlab-runner
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    name: mlflow-ci-secrets
    creationPolicy: Owner
  data:
    - secretKey: MLFLOW_TRACKING_TOKEN
      remoteRef:
        key: app-mlflow-gitlab-token
    - secretKey: GITLAB_TRIGGER_TOKEN
      remoteRef:
        key: app-mlflow-gitlab-trigger-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runner-cache
  namespace: gitlab-runner
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-runner-cache
    creationPolicy: Owner
  data:
    - secretKey: accesskey
      remoteRef:
        key: app-rustfs-access-key
    - secretKey: secretkey
      remoteRef:
        key: app-rustfs-secret-key
