apiVersion: v1
kind: Service
metadata:
  name: matter-server
  namespace: matter-server
  labels:
    app.kubernetes.io/instance: matter-server
    app.kubernetes.io/name: matter-server
spec:
  ports:
    - name: ws
      port: 5580
      protocol: TCP
      targetPort: ws
  selector:
    app.kubernetes.io/instance: matter-server
    app.kubernetes.io/name: matter-server
  type: ClusterIP
