apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- allow-matter-server-access.yaml
namespace: matter-server
labels:
- pairs:
    policy-type: automation-audit
    network-policy: cilium-audit
