/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Homelab Overview",
    },
    {
      type: "category",
      label: "Kubernetes",
      link: {
        type: "generated-index",
        title: "Kubernetes",
        description: "Kubernetes related documentation",
        slug: "/kubernetes",
      },
      items: [
        "kubernetes/index",
        "kubernetes/cluster-access",
        "kubernetes/storage",
        "kubernetes/networking",
        "kubernetes/security",
        "kubernetes/observability",
        "kubernetes/applications",
        "kubernetes/customizations",
        "kubernetes/hardware",
        "kubernetes/backups",
        "kubernetes/ai-assisted-operations",
      ],
    },
    {
      type: "category",
      label: "Hardware",
      link: {
        type: "generated-index",
        title: "Hardware",
        description: "Hardware related documentation",
        slug: "/hardware",
      },
      items: ["hardware/index", "hardware/servers", "hardware/network", "hardware/storage", "hardware/power"],
    },
    {
      type: "category",
      label: "Guides",
      link: {
        type: "generated-index",
        title: "Guides",
        description: "Guides for common tasks",
        slug: "/guides",
      },
      items: ["guides/index", "guides/adding-new-app", "guides/sealed-secrets", "guides/dns"],
    },
    {
      type: "category",
      label: "Breaking Changes",
      collapsible: true,
      collapsed: false, // Show this category expanded by default
      link: {
        type: "generated-index",
        title: "Breaking Changes",
        description: "Important breaking changes and migration guides for the homelab setup.",
        slug: "/breaking-changes",
      },
      items: ["breaking-changes/stateful-migration"], // This ID refers to docs/breaking-changes/stateful-migration.md
    },
    {
      type: "doc",
      id: "todo",
      label: "TODO",
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
