import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  DocumentationSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'doc', id: 'getting-started' },
      items: [
        
        { type: 'autogenerated', dirName: 'getting-started' },
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: ['architecture'],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'infrastructure' }],
    },
    {
      type: 'category',
      label: 'Applications',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'applications' }],
    },
    {
      type: 'category',
      label: 'Kubernetes',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'k8s' }],
    },
    {
      type: 'category',
      label: 'OpenTofu',
      link: { type: 'generated-index' },
      items: [
        'tofu/provisioning-concepts',
        'tofu/provisioning-task-guide',
      ],
    },
    {
      type: 'category',
      label: 'Disaster Recovery',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'disaster' }],
    },
    {
      type: 'category',
      label: 'GitHub',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'github' }],
    },
    {
      type: 'category',
      label: 'Contributing',
      link: { type: 'doc', id: 'contributing/overview' },
      items: [{ type: 'autogenerated', dirName: 'contributing' }],
    },
    {
      type: 'category',
      label: 'Breaking Changes',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'breaking-changes' }],
    },
    {
      type: 'doc',
      id: 'changelog',
      label: 'Changelog',
    },
  ],
};

export default sidebars;
