apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- allow-gitlab-postgresql.yaml
namespace: gitlab
labels:
- pairs:
    policy-type: web-audit
    network-policy: cilium-audit
