apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant

configMapGenerator:
  - name: ha-core-config
    files:
      - config/configuration.yaml

resources:
  - namespace.yaml
  - pvc.yaml
  - http-route.yaml
  - serviceaccount.yaml
  - svc.yaml
  - statefulset.yaml
  - external-secret.yaml
  - ha-mcp-externalsecret.yaml
  - ha-mcp-deployment.yaml
  - ha-mcp-service.yaml
  - ha-mcp-http-route.yaml
  - ha-mcp-network-policy.yaml

generatorOptions:
  disableNameSuffixHash: true
