apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-home-assistant-0
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-csi
  resources:
    requests:
      storage: 5Gi
